a=[]
x=int(input("Enter Max Size:"))
for i in range(x):
    val=input("Enter Value:")
    a.append(val)
print("Original List is:",a)
print("Length of List is:",len(a))
print("Max Value in List is:",max(a))
print("Min Value in List is:",min(a))
b=a
print("Content of list a is:",a)
print("Content of List b is:",b)
z=input("Enter Value to count:")
y=a.count(z)
print(z,"Appears in the List",y,"times.")
z=input("Enter Value Whose Index you want to get:")
index=a.index(z)
print(z,"Found at",index,"Position.")
val=input("Enter Value to insert:")
ind=int(input("Enter index where you want to insert:"))
a.insert(ind,val)
print(a)
val=input("Enter value to remove from the list:")
a.remove(val)
print(a)
print("Original List is:",a)
a.reverse()
print("List after reverse is",a)
a.sort()
print("list after sort is:",a)
print("Last element popped",a.pop())
